//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrthoSquare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMIBajajFinance
    {
        public int EMIID { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public Nullable<int> InvoiceNo { get; set; }
        public Nullable<int> Patientid { get; set; }
        public Nullable<decimal> EMIsAmount { get; set; }
        public Nullable<System.DateTime> DateofEMI { get; set; }
        public Nullable<int> CreateId { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
    }
}
