//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrthoSquare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enquiry
    {
        public int EnquiryID { get; set; }
        public Nullable<int> CatId { get; set; }
        public Nullable<int> Sourceid { get; set; }
        public Nullable<int> PurposeId { get; set; }
        public Nullable<int> ClinicID { get; set; }
        public string Enquiryno { get; set; }
        public Nullable<System.DateTime> EnquiryDate { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public string Age { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> stateid { get; set; }
        public Nullable<int> Cityid { get; set; }
        public string Area { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Telephone { get; set; }
        public Nullable<int> ReceivedByEmpId { get; set; }
        public Nullable<int> AssignToEmpId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Folllowupdate { get; set; }
        public string InterestLevel { get; set; }
        public string InterestLevelCode { get; set; }
        public string Conversation { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsPatient { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> TreatmentID { get; set; }
        public string Pstatus { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> TelecallerToEmpId { get; set; }
    }
}
