//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrthoSquare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseMaster
    {
        public int ExpenseID { get; set; }
        public Nullable<int> ClinicID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public string VendorName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string ExpDetails { get; set; }
        public string ExpBillphoto { get; set; }
        public Nullable<int> CreateID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
