//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrthoSquare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InOutMaterialMaster
    {
        public int InoutID { get; set; }
        public Nullable<int> MaterialId { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> OrderQty { get; set; }
        public Nullable<int> ReceiveQty { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> Receiveddate { get; set; }
        public Nullable<int> CreateId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ClinicID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> OrderPrice { get; set; }
    }
}
