//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrthoSquare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManageMaterialStock
    {
        public int materialstockID { get; set; }
        public Nullable<int> MaterialId { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> TotalMaterial { get; set; }
    }
}
