//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrthoSquare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicinesMaster
    {
        public int MedicinesId { get; set; }
        public Nullable<int> MaterialTypeId { get; set; }
        public string MedicinesName { get; set; }
        public string MedicinesCompany { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
