//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrthoSquare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuRight
    {
        public int ID { get; set; }
        public Nullable<int> MenuID { get; set; }
        public string RoleID { get; set; }
        public Nullable<bool> Page_Add { get; set; }
        public Nullable<bool> Page_Edit { get; set; }
        public Nullable<bool> Page_Delete { get; set; }
        public Nullable<bool> Page_View { get; set; }
    }
}
