//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrthoSquare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthsMaster
    {
        public int MonthID { get; set; }
        public Nullable<int> MonthsName { get; set; }
        public string MonthsCode { get; set; }
        public string MonthsNo { get; set; }
        public Nullable<int> Yearid { get; set; }
    }
}
