//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrthoSquare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientMaster
    {
        public int patientid { get; set; }
        public string PatientCode { get; set; }
        public Nullable<int> EnquiryId { get; set; }
        public Nullable<int> ClinicID { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string FristName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> BOD { get; set; }
        public string BloodGroup { get; set; }
        public string Age { get; set; }
        public string Address { get; set; }
        public string Area { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> stateid { get; set; }
        public Nullable<int> Cityid { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Telephone { get; set; }
        public string ProfileImage { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string PCstatus { get; set; }
        public string registrationToken { get; set; }
    }
}
