//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrthoSquare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientMedicalHistory
    {
        public int ID { get; set; }
        public Nullable<int> patientid { get; set; }
        public string FamilyDoctorName { get; set; }
        public string DrAddress { get; set; }
        public string Pregnant { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string PanMasalaChewing { get; set; }
        public string Tobacco { get; set; }
        public string Somking { get; set; }
        public string cigrattesInDay { get; set; }
        public string ListofMedicine { get; set; }
    }
}
