//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrthoSquare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientbyDentalinfo
    {
        public int DentalinfoID { get; set; }
        public Nullable<int> patientid { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public string Complaint { get; set; }
        public string DentalTreatment { get; set; }
        public string ConsentStatement { get; set; }
        public string ToothNo { get; set; }
        public string ConsentParth { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
    }
}
