//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrthoSquare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetila
    {
        public int PaymentID { get; set; }
        public Nullable<int> InvoiceTid { get; set; }
        public Nullable<int> InvoiceNo { get; set; }
        public string PaymentMode { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string IRFCcode { get; set; }
        public string CheckNo { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string CardNo { get; set; }
        public string BajajFinanceDoc { get; set; }
        public Nullable<decimal> ApprovalAmount { get; set; }
        public Nullable<decimal> InterestinAmount { get; set; }
        public Nullable<decimal> TotalAmountAmount { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public decimal PaidAmount { get; set; }
        public Nullable<decimal> PendingAmount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateID { get; set; }
    }
}
