//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrthoSquare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftwareExpiredMaster
    {
        public int ExpiredID { get; set; }
        public string Year { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
