//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrthoSquare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ClinicDetails
    {
        public int ClinicID { get; set; }
        public string ClinicName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string PhoneNo2 { get; set; }
        public string PhoneNo1 { get; set; }
        public string OpenTime { get; set; }
        public string CloseTime { get; set; }
        public string DayOfWeek { get; set; }
        public string EmailID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public string ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
