//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrthoSquare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DrSpeciality
    {
        public tbl_DrSpeciality()
        {
            this.tbl_DoctorBySpeciality = new HashSet<tbl_DoctorBySpeciality>();
        }
    
        public int SpecialityID { get; set; }
        public string SpecialityName { get; set; }
        public string ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<tbl_DoctorBySpeciality> tbl_DoctorBySpeciality { get; set; }
    }
}
