//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrthoSquare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DoctorBySpeciality
    {
        public int ID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> SpecialityID { get; set; }
        public string ModifiedDate { get; set; }
        public string ModifedBy { get; set; }
    
        public virtual tbl_DrSpeciality tbl_DrSpeciality { get; set; }
    }
}
