//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrthoSquare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeePersonal
    {
        public long EmployeeID { get; set; }
        public Nullable<int> ClinicID { get; set; }
        public string EmployeeCode { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Surname { get; set; }
        public string Gender { get; set; }
        public string Religion { get; set; }
        public string Emp_Cast { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Nationality { get; set; }
        public string EmployeePhoto { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<long> CreatAdmin { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsAdminLogin { get; set; }
    }
}
