//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrthoSquare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeBankDetail
    {
        public long EmployeeBankID { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string IFSC_Code { get; set; }
        public string AccountNumber { get; set; }
        public string AccountHolderName { get; set; }
    }
}
