//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrthoSquare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeOtherDetail
    {
        public int OtherID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string AadhaarNo { get; set; }
        public string PassportNo { get; set; }
        public string DrivinglicenceNo { get; set; }
        public string Documentimg { get; set; }
    }
}
