//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrthoSquare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreatmentbyPatient
    {
        public int ID { get; set; }
        public Nullable<int> patientid { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> TreatmentID { get; set; }
        public string toothNo { get; set; }
        public string StartedTreatments { get; set; }
        public string TreatmentsCost { get; set; }
        public Nullable<System.DateTime> CtrateDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
