//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrthoSquare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsedMaterial
    {
        public int UsedMid { get; set; }
        public Nullable<int> MaterialId { get; set; }
        public Nullable<int> ClinicID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> patientid { get; set; }
        public Nullable<int> ReceiveQty { get; set; }
        public Nullable<int> CreateId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
